# Generated by Django 5.1.3 on 2024-11-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_banner_alter_itemestoque_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
