# Generated by Django 5.1.3 on 2024-11-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
